buildscript {
    repositories {
        mavenCentral()
        google()
        maven { url = 'https://developer.huawei.com/repo/' }
    }
    dependencies {
        classpath libs.gradle
        classpath libs.huawei.agconnect
    }
}

allprojects {
    repositories {
        mavenCentral()
        google()
        maven { url = 'https://developer.huawei.com/repo/' }
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
