
plugins {
    id 'com.android.application'
}

// Only apply the AGCP when dealing with Huawei builds.
def isHuaweiTask = gradle.startParameter.taskNames.any { it.toLowerCase().contains("huawei") || it.toLowerCase().contains("universal") }
if (isHuaweiTask) {
    apply plugin: 'com.huawei.agconnect'
}

android {
    if (System.getenv('SIGNING_KEY_ALIAS') != null) {
        signingConfigs {
            twinmeRelease {
                keyAlias System.getenv('SIGNING_KEY_ALIAS')
                keyPassword System.getenv('SIGNING_KEY_KEY_PASSWORD')
                storeFile file(System.getenv('SIGNING_KEY_STORE_FILE'))
                storePassword System.getenv('SIGNING_KEY_STORE_PASSWORD')
            }
        }
    }
    compileSdkVersion libs.versions.compile.sdk.version.get()
    buildFeatures {
        buildConfig = true
    }
    defaultConfig {
        applicationId "org.twinlife.device.android.twinme"
        minSdkVersion libs.versions.min.sdk.version.get() as int
        targetSdkVersion libs.versions.target.sdk.version.get() as int
        versionCode 526
        versionName "35.2.1"
        manifestPlaceholders.domainName = "twin.me"
        manifestPlaceholders.backupExtension = "twmbckp"

        resourceConfigurations += ["en", "ar", "bg", "cs", "da", "de", "el", "el", "es", "fa", "fi", "fr", "hi", "hr", "hu", "in", "it", "iw", "ja", "ko", "nb", "nl", "pl", "pt", "ro", "ru", "sk", "sl", "sq", "sr", "sv", "tr", "uk", "vi", "zh-rCN", "zh-rTW"]
    }
    namespace = 'org.twinlife.device.android.twinme'
    compileOptions {
        coreLibraryDesugaringEnabled = true

        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildTypes {
        // Production settings and build parameters.
        // The APK/AAB must be produced with this build type.
        release {
            shrinkResources = true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

            applicationIdSuffix ""

            buildConfigField "String", 'APPLICATION_ID_SUFFIX', '""'
            buildConfigField "String", 'ACCOUNT_ACTIVITY', '"org.twinlife.twinme.ui.AccountActivity"'
            buildConfigField "String", "CHECK_VERSION_URL", "\"https://twin.me/download/twinme.json\""
            buildConfigField "String", "FAQ_URL", "\"https://twin.me/download/faq-twinme.json\""
            buildConfigField "String", "FILE_PROVIDER", '"org.twinlife.device.android.twinme.fileprovider"'
            buildConfigField "String", "FLAVOR", '""'
            buildConfigField "boolean", "DISPLAY_PREMIUM_FEATURE", "true"
            buildConfigField "String", "INVITATION_PARAM_ID", '"twincodeId"'
            buildConfigField "String", "BACKUP_EXTENSION", '"twmbckp"'

            manifestPlaceholders.domainName = "twin.me"
            manifestPlaceholders.twinmePackage = "org.twinlife.device.android.twinme"

            if (System.getenv('SIGNING_KEY_ALIAS') != null) {
                signingConfig signingConfigs.twinmeRelease
            }
        }

        // Production settings, dev build parameters.
        // Use this build type to test the app on the production environment when making a release.
        staging {
            initWith buildTypes.release
            //noinspection NotShrinkingResources
            shrinkResources = false
            minifyEnabled false
            debuggable true

            signingConfig = signingConfigs.debug

            applicationIdSuffix ".staging"
            buildConfigField "String", 'APPLICATION_ID_SUFFIX', '".staging"'
            buildConfigField "String", "BACKUP_EXTENSION", '"twmbckp"'
        }

        // Dev settings and build parameters.
        // Use to run the app during the development cycle.
        debug {
            applicationIdSuffix ".debug"
            debuggable true
            buildConfigField "String", 'APPLICATION_ID_SUFFIX', '".debug"'

            buildConfigField "String", 'ACCOUNT_ACTIVITY', '"org.twinlife.twinme.ui.DebugAccountActivity"'
            buildConfigField "String", "CHECK_VERSION_URL", "\"https://invite.mytwinlife.net/download/twinme.json\""
            buildConfigField "String", "FAQ_URL", "\"https://invite.mytwinlife.net/download/faq-twinme.json\""
            buildConfigField "boolean", "DISPLAY_PREMIUM_FEATURE", "true"
            buildConfigField "String", "FILE_PROVIDER", '"org.twinlife.device.android.twinme.fileprovider"'
            buildConfigField "String", "FLAVOR", '"Development"'
            buildConfigField "String", "INVITATION_PARAM_ID", '"twincodeId"'

            manifestPlaceholders.domainName = "mytwinlife.net"
            manifestPlaceholders.twinmePackage = "org.twinlife.device.android.twinme.debug"

            signingConfig = signingConfigs.debug

            getIsDefault().set(true)
        }
    }

    flavorDimensions = ["product", "tier", "distribution"]

    productFlavors {
        // Needed to setup twinlife & twinme product dimension
        skred {
            dimension "product"
        }
        twinme {
            dimension "product"
            getIsDefault().set(true)
        }

        //Skred and Twinme
        free {
            dimension "tier"
            getIsDefault().set(true)
        }

        //Twinme+
        '+' {
            dimension "tier"
        }

        google {
            dimension "distribution"
            getIsDefault().set(true)
        }
        huawei {
            dimension "distribution"
        }
        // universal => both google (firebase) and huawei push services are available.
        // If firebase token creation fails, huawei will be tried as a fallback.
        universal {
            dimension "distribution"
        }
    }

    bundle {
        language {
            enableSplit = false
        }
    }

    packaging {
        resources {
            // Since the inclusion of Huawei's gradle plugin, these files trigger a duplicate resources conflict during build.
            excludes += [
                    "META-INF/DEPENDENCIES",
                    "migrateToAndroidx/migration.xml",
                    "META-INF/INDEX.LIST",
                    "META-INF/io.netty.versions.properties",
                    "r8-version.properties"
            ]
        }
    }
}

androidComponents {
    // Only define necessary variants (Skred only has a free tier)
    beforeVariants(
            selector()
                    .withFlavor("product", "skred")
                    .withFlavor("tier", "+")
    ) { variantBuilder ->
        variantBuilder.enable = false
    }

    onVariants(
            selector().all()
    ) { variant ->
        def distro = variant.productFlavors.find { it.first == "distribution" }?.second ?: ""
        def buildType = variant.buildType

        if (buildType == "staging") {
            // Use release source sets for staging builds.
            buildType = "release"
        }

        def addTwinmeSources = { dirName ->
            variant.sources.java.addStaticSourceDirectory("src/${dirName}/java")
            variant.sources.res.addStaticSourceDirectory("src/${dirName}/res")
            variant.sources.resources.addStaticSourceDirectory("src/${dirName}/resources")
        }

        // Setup common distribution source sets (e.g. src/huaweiDebug/res)
        addTwinmeSources("${distro}${buildType.capitalize()}")

        if (distro == "universal") {
            variant.sources.java.addStaticSourceDirectory("src/google/java")
            variant.sources.java.addStaticSourceDirectory("src/huawei/java")
        }
    }
}

dependencies {

    implementation project(':twinlife-framework')
    implementation project(':webrtc-framework')
    implementation project(':twinme-framework')
    implementation project(':twinme-android-common')
    implementation project(':zxing')
    implementation project(':image-cropper')

    implementation libs.androidx.appcompat
    implementation libs.androidx.recyclerview
    implementation libs.material
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.media
    implementation libs.androidx.media3.transformer
    implementation libs.androidx.core.splashscreen
    implementation libs.androidx.browser
    implementation libs.lottie
    implementation libs.glide
    implementation libs.glide.recyclerview

    implementation libs.installreferrer

    coreLibraryDesugaring libs.desugar.jdk.libs

    // Support for Chooser Target (Replaced by direct share targets in Android 10)
    runtimeOnly libs.androidx.sharetarget

    // debugImplementation because LeakCanary should only run in debug builds.
    debugImplementation libs.leakcanary.android
}

// Huawei's gradle plugin v1.9.5.301 has a transitive dependency to protobuf-java.
// We can try removing this when we upgrade the plugin.
configurations.configureEach {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.requested.group == 'com.google.protobuf' && details.requested.name == 'protobuf-java') {
            // Force the use of the lite version which is compatible with min-api < 26, and generally recommended for Android.
            details.useTarget 'com.google.protobuf:protobuf-javalite:3.21.12'
        }
    }
}